#!/bin/sh

export PYTHONHOME=$(pwd)/src

poetry run gunicorn --bind 0.0.0.0:5000 \
    --graceful-timeout 5 \
    -k flask_sockets.worker --reload "pinochle.wsgi:application" "$@"
    # --reload "pinochle.wsgi:application" "$@"
